CupCarbon v. IoT 5.2
----------------
name:Punto 1
zoom:4
centerposition_la:4.653280408186506
centerposition_lo:-74.06114697685037
map:0
display_details:true
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:0
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:false
